// background.js

// When the user clicks the extension icon, open the app in a new full tab.
// This prevents the popup from closing and cancelling the upload if they click elsewhere.
chrome.action.onClicked.addListener((tab) => {
    chrome.tabs.create({
        url: 'index.html' // This will be the UI page generated by Stitch
    });
});
